/**
 * Turn a picked DOM element into the selector candidates a step is resolved with.
 *
 * Classic script, not a module: `content_scripts` cannot load ES modules. It is listed
 * after vendor/guide-schema.global.js so `GUIDE_SCHEMA.normalizeText` is available —
 * the recorder must produce text the SAME way the matcher compares it.
 *
 * The rules here are written against what the POS audit actually measured, not against
 * what a generic picker would do:
 *
 *   - `#basic-button` exists NINE times on one POS page, and the v4 config used it 14
 *     times. So an id is never trusted on sight: every candidate is counted against the
 *     live document and only kept when it resolves to exactly one element.
 *   - `css-jj9uz9` is an emotion/MUI class regenerated on every build, so class names
 *     that look generated are dropped before they can be baked into a guide.
 *   - 347 of 409 legacy selectors were `:nth-of-type` chains, which is why 333 of them
 *     depend on the DOM tree. A structural path is produced LAST, only as the fallback
 *     when nothing stable was found.
 *   - Text is the most reliable anchor measured on POS ("Cài Đặt" matches exactly one
 *     button), so matchText is always captured when it is short enough to be an anchor.
 *
 * Pure with respect to the browser: everything that needs the document is reached
 * through the injected `count(selector) -> number`, so this is unit-testable.
 */

(function (root) {
  "use strict";

  /** Longest text still usable as an anchor. Past this it is a container, not a label. */
  var MAX_TEXT = 120;

  /** How many candidates a step carries. More than this is noise the runtime never reaches. */
  var MAX_CANDIDATES = 4;

  /** Attributes an application sets on purpose; safe to pin a selector on. */
  var STABLE_ATTRS = [
    "data-testid",
    "data-test",
    "data-testid-id",
    "data-qa",
    "data-cy",
    "name",
    "aria-label",
    "placeholder",
    "type",
  ];

  /** Class names that are regenerated by the build and mean nothing tomorrow. */
  var GENERATED_CLASS = [
    /^css-[a-z0-9]+$/i, // emotion / MUI — POS ships css-jj9uz9
    /^sc-[a-zA-Z0-9]{5,}$/, // styled-components
    /^jsx-\d+$/, // styled-jsx
    /^emotion-/i,
    /__[A-Za-z0-9_-]{5,}$/, // CSS modules: Home_main__nSbtS
    /^[A-Za-z]+-[a-z0-9]{8,}$/, // hashed utility, e.g. btn-1f3a9c7e
  ];

  /** Ids that are framework-generated rather than authored. */
  var GENERATED_ID = [
    /^:r[0-9a-z]+:$/i, // React useId
    /^radix-/i,
    /^headlessui-/i,
    /^mui-[0-9]+$/i,
    /^[0-9a-f]{8}-[0-9a-f]{4}-/i, // uuid
    /^[0-9]+$/, // a bare row number
  ];

  var INTERACTIVE_TAGS = ["a", "button", "input", "select", "textarea", "label", "summary"];
  var INTERACTIVE_ROLES = ["button", "link", "menuitem", "tab", "option", "checkbox", "radio", "switch"];

  function anyMatch(patterns, value) {
    for (var i = 0; i < patterns.length; i++) if (patterns[i].test(value)) return true;
    return false;
  }

  function tagOf(el) {
    return String((el && el.tagName) || "").toLowerCase();
  }

  function attr(el, name) {
    if (!el || typeof el.getAttribute !== "function") return "";
    var v = el.getAttribute(name);
    return v === null || v === undefined ? "" : String(v);
  }

  function classesOf(el) {
    var raw = attr(el, "class");
    if (!raw) return [];
    return raw.split(/\s+/).filter(Boolean);
  }

  function isStableId(id) {
    var s = String(id || "").trim();
    if (!s || s.length > 60) return false;
    if (anyMatch(GENERATED_ID, s)) return false;
    return true;
  }

  function isStableClass(cls) {
    var s = String(cls || "").trim();
    if (!s || s.length > 40) return false;
    return !anyMatch(GENERATED_CLASS, s);
  }

  /**
   * A CSS identifier, or "" when the value has to go through an attribute selector
   * instead. `CSS.escape` is not reachable from a unit test and is overkill here: the
   * only two shapes that matter are "a plain identifier" and "anything else".
   */
  function asIdentifier(value) {
    var s = String(value || "");
    return /^-?[A-Za-z_][\w-]*$/.test(s) ? s : "";
  }

  function quote(value) {
    return '"' + String(value || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
  }

  /** `#id` when the id is a plain identifier, `[id="…"]` when it is not. */
  function idSelector(id) {
    var ident = asIdentifier(id);
    return ident ? "#" + ident : "[id=" + quote(id) + "]";
  }

  /* --------------------------------------------------------------- candidates */

  /**
   * Selectors for `el` that do not depend on its position in the tree, best first.
   * Uniqueness is NOT checked here — the caller decides what to do with a duplicate.
   */
  function ownSelectors(el) {
    var out = [];
    var tag = tagOf(el);
    if (!tag) return out;

    var id = attr(el, "id");
    if (id && isStableId(id)) out.push(idSelector(id));

    for (var i = 0; i < STABLE_ATTRS.length; i++) {
      var name = STABLE_ATTRS[i];
      var value = attr(el, name);
      // `type` alone is meaningless; it only narrows an already-narrow tag.
      if (!value || value.length > 80) continue;
      if (name === "type" && tag !== "input" && tag !== "button") continue;
      out.push(tag + "[" + name + "=" + quote(value) + "]");
    }

    var stable = classesOf(el).filter(isStableClass).slice(0, 3);
    if (stable.length) {
      var idents = [];
      for (var c = 0; c < stable.length; c++) {
        var ident = asIdentifier(stable[c]);
        if (ident) idents.push("." + ident);
      }
      if (idents.length) out.push(tag + idents.join(""));
    }

    return out;
  }

  /** 1-based index of `el` among the siblings that share its tag. */
  function nthOfType(el) {
    var parent = el && el.parentElement;
    if (!parent) return 1;
    var siblings = parent.children || [];
    var tag = tagOf(el);
    var n = 0;
    for (var i = 0; i < siblings.length; i++) {
      if (tagOf(siblings[i]) === tag) {
        n++;
        if (siblings[i] === el) return n;
      }
    }
    return n || 1;
  }

  function segment(el) {
    return tagOf(el) + ":nth-of-type(" + nthOfType(el) + ")";
  }

  /**
   * A path anchored on the closest ancestor that IS uniquely addressable.
   *
   * This is the difference between a selector that survives a re-render and the legacy
   * `div > div:nth-of-type(3) > ...` chains: the anchor carries the meaning, and only
   * the last couple of hops are structural.
   */
  function anchoredPath(el, count, maxUp) {
    // Nodes BELOW `cur`, nearest-to-root first — `cur` itself is never in here, which is
    // why it has to be prepended and not appended when the anchor is found. Getting that
    // backwards produces a selector that reads plausibly and matches nothing.
    var below = [];
    var cur = el;
    var up = 0;
    while (cur && up <= maxUp) {
      var parent = cur.parentElement;
      if (!parent) break;
      var own = ownSelectors(parent);
      for (var i = 0; i < own.length; i++) {
        if (count(own[i]) === 1) {
          return own[i] + " > " + [segment(cur)].concat(below).join(" > ");
        }
      }
      below.unshift(segment(cur));
      cur = parent;
      up++;
    }
    return "";
  }

  /** Last resort: a structural path from the document root, capped so it stays readable. */
  function structuralPath(el, maxDepth) {
    var parts = [];
    var cur = el;
    while (cur && parts.length < maxDepth) {
      var tag = tagOf(cur);
      if (!tag || tag === "html") break;
      if (tag === "body") {
        parts.unshift("body");
        break;
      }
      parts.unshift(segment(cur));
      cur = cur.parentElement;
    }
    return parts.join(" > ");
  }

  /**
   * The candidate list for a step, most stable first.
   *
   * @param {Element} el     the element the operator picked
   * @param {(sel: string) => number} count  how many elements a selector resolves to
   */
  function buildCandidates(el, count) {
    var safeCount = function (sel) {
      try {
        return count(sel);
      } catch (err) {
        return 0;
      }
    };

    var unique = [];
    var ambiguous = [];

    var own = ownSelectors(el);
    for (var i = 0; i < own.length; i++) {
      var n = safeCount(own[i]);
      if (n === 1) unique.push(own[i]);
      else if (n > 1) ambiguous.push(own[i]);
    }

    // Count it like any other candidate. A path that resolves to NOTHING must never be
    // emitted: the runtime would walk to it, find nothing, and fall through — and the
    // structural fallback behind it would hide the fact that the anchor was wrong.
    var anchored = anchoredPath(el, safeCount, 5);
    var anchoredCount = anchored ? safeCount(anchored) : 0;
    if (anchoredCount === 1) unique.push(anchored);
    else if (anchoredCount > 1) ambiguous.push(anchored);

    var out = [];
    var push = function (sel) {
      if (sel && out.indexOf(sel) < 0 && out.length < MAX_CANDIDATES) out.push(sel);
    };

    // Unique first. An ambiguous selector is still worth carrying: the runtime narrows a
    // multi-match by matchText, and that is how "Cài Đặt" resolves on POS. It just must
    // never be the PRIMARY candidate when something unique exists.
    unique.forEach(push);
    ambiguous.forEach(push);

    // Only when nothing addressable was found. A structural path that sits BEHIND a
    // working selector is not a safety net: if the good selector ever stops matching,
    // the path resolves to whatever element now happens to sit at that position, and
    // the step silently points at the wrong thing. 347 of the 409 legacy steps were
    // exactly this kind of path, which is why it is the fallback and not a companion.
    if (!unique.length) push(structuralPath(el, 8));
    return out;
  }

  /* --------------------------------------------------------------------- text */

  function normalize(text) {
    var schema = root.GUIDE_SCHEMA;
    // One definition of text normalization. If the bundle is missing the recorder must
    // fail loudly rather than invent a second, drifting one.
    if (!schema || typeof schema.normalizeText !== "function") {
      throw new Error("GUIDE_SCHEMA.normalizeText chưa được nạp — không thể ghi matchText.");
    }
    return schema.normalizeText(text);
  }

  /**
   * The text anchor for a step.
   *
   * Never truncated: a step whose matchText is a cut-off prefix would fail every exact
   * comparison at runtime, which is worse than having no anchor at all. Long text means
   * the operator picked a container, so the label attributes are tried instead.
   */
  function pickText(el) {
    var own = normalize((el && (el.innerText || el.textContent)) || "");
    if (own && own.length <= MAX_TEXT) return own;

    var labels = ["aria-label", "title", "placeholder", "alt"];
    for (var i = 0; i < labels.length; i++) {
      var v = normalize(attr(el, labels[i]));
      if (v && v.length <= MAX_TEXT) return v;
    }

    var value = el && typeof el.value === "string" ? normalize(el.value) : "";
    return value && value.length <= MAX_TEXT ? value : "";
  }

  /* ----------------------------------------------------------------- element */

  function isInteractive(el) {
    if (!el) return false;
    if (INTERACTIVE_TAGS.indexOf(tagOf(el)) >= 0) return true;
    var role = attr(el, "role").toLowerCase();
    if (INTERACTIVE_ROLES.indexOf(role) >= 0) return true;
    return attr(el, "contenteditable") === "true";
  }

  /**
   * Clicking a button's label hands us the inner <span>. The operator means the button,
   * and the button is also what carries the stable attributes — so climb a few levels
   * to the nearest interactive ancestor before describing anything.
   */
  function interactiveTarget(el) {
    var cur = el;
    var up = 0;
    while (cur && up < 4) {
      if (isInteractive(cur)) return cur;
      cur = cur.parentElement;
      up++;
    }
    return el;
  }

  /** Everything a recorded step needs from the DOM. */
  function describe(el, count) {
    return {
      selectors: buildCandidates(el, count),
      matchText: pickText(el),
      tag: tagOf(el),
    };
  }

  root.TG_SELECTOR = Object.freeze({
    MAX_TEXT: MAX_TEXT,
    MAX_CANDIDATES: MAX_CANDIDATES,
    STABLE_ATTRS: STABLE_ATTRS,
    isStableId: isStableId,
    isStableClass: isStableClass,
    asIdentifier: asIdentifier,
    idSelector: idSelector,
    ownSelectors: ownSelectors,
    nthOfType: nthOfType,
    anchoredPath: anchoredPath,
    structuralPath: structuralPath,
    buildCandidates: buildCandidates,
    pickText: pickText,
    isInteractive: isInteractive,
    interactiveTarget: interactiveTarget,
    describe: describe,
  });
})(typeof globalThis !== "undefined" ? globalThis : self);
